# service manifest for webapp
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
labels:
  app: webapp
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
    type: NodePort # expose the service on the node port